### ISSUE TITLE
Grade Comments

### ISSUE THREAD

**Issue by andrewclavin** [TheLuomamr/LIRI_BOT#1]
Lets for the win!! great job, but let's(pun) start using const if we aren't reassigning the value! Good job the with readme and the gitignore too! 
Now that we're starting to get into es15 let's keep going and beyond. In the coming weeks let's try to use some of the following...

async await, instead of using the .then, you give the surrounding function context of where the then is added the keyword async, so like instead of:

```
function(){
  [...other code]
  funcThatReslovesAPromise(arguments).then(function(){
      stuff to do
  })
 [...other code]
}
```
try:

```
async function(){
  await functThatReslovesAPromise
  stuff to do
}
```
and/or try playing with arrow function (also called a lambda), instead of function(){} you can just go () => {}, especially nice when you're passing a function in as a callback like in the then thing above... now there is a difference in a special thing with the arrow function, but at first it's just good to get use to being comfortable using them.

**Comment by TheLuomamr** [comment]
Thanks for the tips Andrew, appreciate the help!
